title: めもちょう
description: Markunet log

url: https://markunet.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate, jekyll-sitemap]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Articles
   url: /articles
 - title: Categories
   url: /categories
 - title: About
   url: /about

social:
   github: markunet
   linkedin: markunet
   facebook:
   email:

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      comments: false

# Google Analytics
google_analytics: "UA-181625934-1"

# development configurations
host: 0.0.0.0